### ISSUE TITLE
CSS User Storys

### ISSUE THREAD

**Issue by elir0d** [roelisontrindade/Build-a-Product-Landing-Page-FCC#2]
- [x] User Story #13: The navbar should always be at the top of the viewport.

- [x] User Story #14: My product landing page should have at least one media query.

- [x] User Story #15: My product landing page should utilize CSS flexbox at least once.

**Comment by elir0d** [comment]
CSS File Seted
